# Generated by Django 4.1.7 on 2023-02-27 14:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=30)),
                ('afegit', models.DateField(default=datetime.date(2023, 2, 27))),
                ('usuaris', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Videojoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=30)),
                ('preu', models.FloatField(default=0)),
                ('nou', models.BooleanField(default=False)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Videojocs.plataforma')),
            ],
        ),
    ]
