# Generated by Django 4.1.7 on 2023-02-28 22:15

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Videojocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojoc',
            name='usuaris',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='afegit',
            field=models.DateField(default=datetime.datetime(2023, 2, 28, 22, 15, 12, 917631, tzinfo=datetime.timezone.utc)),
        ),
    ]
